image: maven:3-jdk-11

before_script:
  - echo "Running App Hub CI/CD"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - ugrad
  script: "mvn compile"

test:
  stage: test
  tags:
    - ugrad
  script: "mvn test"
  artifacts:
      when: always
      reports:
        junit:
          - $CI_PROJECT_DIR/target/surefire-reports/TEST-*.xml
          - $CI_PROJECT_DIR/target/failsafe-reports/TEST-*.xml


deploy:
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV  --api-key=$HEROKU_API_KEY
  only:
    - develop
    - master

after_script:
  - echo "App Hub CI/CD completed"
